env:
  global:
    secure: cIULPfjcs8l+iYwSP9F8zStXqQVO7bg1A31c6yU/LE91n5226TiuM0QgdisBrt4p14usvzx5XvEOB1QifC7a9q2xHAg3HjAfoKHnU8GG4rmGk2y/HB07ZR5wPBgGvB42l6NRScxLCZvlU7ETl/hqFuXxLT03Wau0noIjNr7ESTooFqRaMO7origet1kMDHkVcIzanHQs1yfNJKpTLcwxfZbQrQR1oiBrcldqT7ZEqcpymHOrSkp96wEF/VuCMw76toyh+ktrrrciomkUpxYoDx7AxDp1OAUCMSB/z6QJrKZax5KROmc5ymSyA5lvW2u94Z9mB0sSjMbPxBpFiNSioN53FJfMope598VG65BrTMq6T4ZvP14Gsq7AqsN3+nHuxysSsVTMU8gsr95uwhh3AHt5IpXtiPM5eAHTKCVYJgT49JWoUwF+dITm2UdLRdOocxoi/CXAAQ6/shJDIh/zlF8K4LHbO/T4IJAOXy1ThGVxMW77sIkSzyke+H82SOhmHr28H35HCa6ZyPq+7tGvD27hpZBHgKl+jI3PhZq7b1O1ZuD/ds7mYejH3uADGULb2xG01i8kUCI61X5eUOHfTNrWUYPxqWCS9WWVk9fuJqWYfILUjc9dV9ftC9AGYDmnysqt2bYUZmstPxnofThsgVnAhlGtd3ezqx8tXyHJpXM=

sudo: false

language: python
before_install:
  - git remote set-url origin https://${GH_TOKEN}@github.com/NOVAAPI/docs/ > /dev/null 2>&1
  - git fetch origin gh-pages > /dev/null 2>&1
install: pip install mkdocs
script: mkdocs gh-deploy --clean > /dev/null 2>&1
